# Generated by Django 5.1.4 on 2025-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buttonclickstats_delete_buttonclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonclickstats',
            name='click_count',
            field=models.IntegerField(default=1),
        ),
    ]
